### ISSUE TITLE
Can't get it to work, homebridge keeps crashing

### ISSUE THREAD

**Issue by zabaya** [paolotremadio/homebridge-automation-chromecast#11]
Everytime i try to install the accesory in the accesory tab, my homebridge is stuck. It's searching for the device, and then this error shows up and it reboots
```
[12/31/2019, 3:23:12 PM] Error: getaddrinfo -3008
    at errnoException (/homebridge/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
    at getaddrinfo_complete (/homebridge/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
    at GetAddrInfoReqWrap.oncomplete (/homebridge/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)

[12/31/2019, 3:23:12 PM] Got SIGTERM, shutting down Homebridge...
```

**Comment by paolotremadio** [comment]
How do you run your homebridge instance? What’s the OS/platform?

**Comment by zabaya** [comment]
Welll, i didn't think you would answer today, of all days. I run it on a raspberry pi through docker (alpine).

**Comment by paolotremadio** [comment]
Docker is not currently supported. This plugins uses mDNS/Bonjour to detect the Chromecast device. mDNS requires multicast support. I suspect a different code is required for running into docker. I would suggest you run it directly on the Raspberry host. There's no benefit in running it into Docker.

**Comment by paolotremadio** [comment]
@zabaya what plugins do you have installed on your homebridge instance? I'm looking for clues on what code is required.

**Comment by zabaya** [comment]
Quite some actually, but they mostly connect to the api from the original webapps.

Homebridge Tuya Web
Homebridge Broadlink Rm Tv
Homebridge Config UI X
Homebridge Ewelink Max
Homebridge Away Mode
Homebridge Alexa
Homebridge Automation Switches
Homebridge Cmdswitch2
Homebridge Dacp

I also tried reinstalling homebridge in a clean install of buster without any other plugins but now i get different errors. 

```
npm i -g homebridge-automation-chromecast --unsafeperm

> mdns@2.5.1 install /usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:
../src/mdns.hpp:32:10: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
          ^~~~~~~~~~
compilation terminated.
make: *** [dns_sd_bindings.target.mk:174: Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.75-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-01-03T14_02_00_955Z-debug.log
```

**Comment by zabaya** [comment]
```
npm i -g homebridge-automation-chromecast --unsafeperm

> mdns@2.5.1 install /usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:
../src/mdns.hpp:32:10: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
          ^~~~~~~~~~
compilation terminated.
make: *** [dns_sd_bindings.target.mk:174: Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.75-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-01-03T14_02_00_955Z-debug.log
```

**Comment by Salvora** [comment]
> 
> 
> @zabaya what plugins do you have installed on your homebridge instance? I'm looking for clues on what code is required.

This could help though I am not sure. I have the same issue with mdns. Running on Synology Docker.
https://github.com/oznu/mdns-resolver

**Comment by joconcepts** [comment]
Same issue here. Also running homebridge in docker. I've already tried that:
https://github.com/moby/moby/issues/32106

**Comment by paolotremadio** [comment]
Has anyone managed to run any other bonjour/mdns plugins on docker? So I can have a look on how they've solved this issue as I can't reproduce at the mo :|

**Comment by Salvora** [comment]
Well,
I tried to install this plugin directly to the raspian homebridge but the result was the same. Installation was failure.
sudo npm i -g homebridge-control-chromecast


Node.js: v12.16.1
Npm: v6.14.3

```
1893 silly install hap-nodejs@0.4.53
1894 info lifecycle hap-nodejs@0.4.53~install: hap-nodejs@0.4.53
1895 silly install mdns@2.5.1
1896 info lifecycle mdns@2.5.1~install: mdns@2.5.1
1897 verbose lifecycle mdns@2.5.1~install: unsafe-perm in lifecycle true
1898 verbose lifecycle mdns@2.5.1~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/node_modules/.bin:/usr/lib/node_modules/homebridge-automation-chromecast/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
1899 verbose lifecycle mdns@2.5.1~install: CWD: /usr/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns
1900 silly lifecycle mdns@2.5.1~install: Args: [ '-c', 'node-gyp rebuild' ]
1901 silly lifecycle mdns@2.5.1~install: Returned: code: 1  signal: null
1902 info lifecycle mdns@2.5.1~install: Failed to exec install script
1903 timing action:install Completed in 1507ms
1904 verbose unlock done using /home/homebridge/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
1905 timing stage:rollbackFailedOptional Completed in 467ms
1906 timing stage:runTopLevelLifecycles Completed in 13028ms
1907 verbose stack Error: mdns@2.5.1 install: `node-gyp rebuild`
1907 verbose stack Exit status 1
1907 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
1907 verbose stack     at EventEmitter.emit (events.js:311:20)
1907 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
1907 verbose stack     at ChildProcess.emit (events.js:311:20)
1907 verbose stack     at maybeClose (internal/child_process.js:1021:16)
1907 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
1908 verbose pkgid mdns@2.5.1
1909 verbose cwd /usr/lib
1910 verbose Linux 4.19.97-v7l+
1911 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "homebridge-automation-chromecast@latest"
1912 verbose node v12.16.1
1913 verbose npm  v6.14.3
1914 error code ELIFECYCLE
1915 error errno 1
1916 error mdns@2.5.1 install: `node-gyp rebuild`
1916 error Exit status 1
1917 error Failed at the mdns@2.5.1 install script.
1917 error This is probably not a problem with npm. There is likely additional logging output above.
1918 verbose exit [ 1, true ]
```
Btw, I've run this command to install libdnssd. It didn't help.
sudo apt-get install libavahi-compat-libdnssd-dev
trying to install mdns package was also failure.
sudo npm install -g mdns

**Comment by zabaya** [comment]
I've reinstalled homebridge without docker and it works fine. So for me this issue is closed.

**Comment by paolotremadio** [comment]
Brilliant. Docker is a known issue

**Comment by bm1549** [comment]
I experienced the same issue as @salvora when attempting to install directly on Raspbian on a Raspberry Pi. Is there any workaround for running this on a Pi?

**Comment by paolotremadio** [comment]
> I experienced the same issue as @Salvora when attempting to install directly on Raspbian on a Raspberry Pi. Is there any workaround for running this on a Pi?

What command are you using to install the plugin?

**Comment by bm1549** [comment]
I ran `sudo -E -n npm install homebridge-automation-chromecast@latest`

**Comment by paolotremadio** [comment]
> I ran `sudo -E -n npm install homebridge-automation-chromecast@latest`

Try  `sudo -E -n npm install https://github.com/paolotremadio/homebridge-automation-chromecast`

I’ve made some changes pending release. It should help with your issue. Let me know if it works.

**Comment by bm1549** [comment]
That just worked for me. Thank you!

**Comment by paolotremadio** [comment]
> That just worked for me. Thank you!

Perfect. I will publish it 😉
