### ISSUE TITLE
Homebridge crashing

### ISSUE THREAD

**Issue by Reemuson** [paolotremadio/homebridge-automation-chromecast#17]
Hello, I seem to be having similar issues to #11 and #9. But my circumstances are different. I am running HB on my Arch server with avahi-daemon installed. I am getting a similar if not identical error message and my HB crashes and restarts.

`Error: getaddrinfo -3008
    at errnoException (/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
    at getaddrinfo_complete (/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
    at GetAddrInfoReqWrap.oncomplete (/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)`

Any ideas as to what this could be? I've been trying to find a way to link my Chromecasts to HomeKit and the other plugins out there all don't seem to work either.

**Comment by paolotremadio** [comment]
It’s an issue with the mDNS resolver. I did research into it but there’re tons of possible solutions (mainly guesses) that don’t necessarily work. The main problem is: I don’t have an env where I can reproduce the issue so it is really difficult for me to patch it :| 

You’re more than welcome to try some of the solutions and issue a pull request
