### ISSUE TITLE
Impossible to install

### ISSUE THREAD

**Issue by yceballost** [paolotremadio/homebridge-automation-chromecast#18]
Hi, I am having problem installing this plugin with homebridge

```

> mdns@2.5.1 install /usr/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/usr/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:
../src/mdns.hpp:32:10: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
          ^~~~~~~~~~
compilation terminated.
make: *** [dns_sd_bindings.target.mk:177: Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/usr/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.118-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2020-07-22T05_50_24_606Z-debug.log

Command failed. Please review log for details.
```

**Comment by paolotremadio** [comment]
What platform are you on? What command are you using to install it?

**Comment by yceballost** [comment]
i'm using the plugin Homebridge Config UI X with Homebridge Insecure Mode enabled.

The command is 
`sudo -E -n npm install homebridge-automation-chromecast@latest`

**Comment by paolotremadio** [comment]
@donavanbecker do you have any idea on how to fix this on config UI? Otherwise I’ll have to remove the UI config. This is not the first PR and I can’t afford to offer support for it right now :|

**Comment by ckeech** [comment]
I’m having the same issue in raspberry pi running Raspberry OS. Previously I was using the homebridge pre built SD image and I was able to install this plugin however since I installed homebridge on raspberry pi OS following the guide I get this error when trying to install this plugin too. Thanks.

**Comment by paolotremadio** [comment]
> I’m having the same issue in raspberry pi running Raspberry OS. Previously I was using the homebridge pre built SD image and I was able to install this plugin however since I installed homebridge on raspberry pi OS following the guide I get this error when trying to install this plugin too. Thanks.

How are you trying to install? What command are you running?

Could you please paste the output of the following commands: 
```
uname -a

whoami
```

**Comment by ckeech** [comment]
Thanks for the quick reply. I'm installing using "Homebridge Config UI X"

Error is:
```
USER: homebridge
DIR: /usr/lib
CMD: sudo -E -n npm install homebridge-automation-chromecast@latest


> mdns@2.5.1 install /usr/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/usr/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:
../src/mdns.hpp:32:10: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
          ^~~~~~~~~~
compilation terminated.
make: *** [dns_sd_bindings.target.mk:177: Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/usr/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.51-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdns@2.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2020-08-21T22_38_28_600Z-debug.log

Command failed. Please review log for details.
```

```
uname -a
Linux 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux
```

```
whoami
homebridge
```

**Comment by paolotremadio** [comment]
Try run run:

`sudo apt-get install libavahi-compat-libdnssd-dev` and install the plugin again. Let me know if it works

**Comment by ckeech** [comment]
That fixed it! Thank you so much. Have a great day.
