### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by atcen** [paolotremadio/homebridge-automation-chromecast#19]
I've added my Chromecast with hardcoded IP. Because name detection didn't worked. 
After this i found this in the log. 

Maybe this was the problem the whole time.

Still it doesn't work to detect my chromecast....

`[01/03/2021, 20:14:05] TypeError: Cannot read property 'toLowerCase' of undefined
    at Browser.<anonymous> (/usr/local/lib/node_modules/homebridge-automation-chromecast/index.js:112:60)
    at Browser.emit (events.js:315:20)
    at on_resolver_done (/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/lib/browser.js:31:14)
    at next (/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/lib/browser.js:106:7)
    at Array.makeAddressesUnique (/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/lib/resolver_sequence_tasks.js:177:5)
    at next (/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/lib/browser.js:109:21)
    at /usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/lib/resolver_sequence_tasks.js:160:11
    at getaddrinfo_complete (/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/lib/resolver_sequence_tasks.js:108:7)
    at GetAddrInfoReqWrap.oncomplete (/usr/local/lib/node_modules/homebridge-automation-chromecast/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)`

**Comment by paolotremadio** [comment]
Hi, thanks for reporting the issue. I think I know what the bug is. Do you mind posting your homebridge config json? It will help me debug the issue.
