### ISSUE TITLE
Homebridge crash

### ISSUE THREAD

**Issue by pax0707** [paolotremadio/homebridge-automation-chromecast#2]
This can happen 1-3 times a day.

Is it something obvious or should I leave it debugging?

```
[2018-4-19 23:41:38] [Chromecast] Chromecast found on 172.16.1.31:8009
[2018-4-19 23:41:38] [Chromecast] Connecting to Chromecast on 172.16.1.31:8009
[2018-4-19 23:41:38] [Chromecast] Chromecast connection: connected
Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:713:20)
    at ChildProcess.target.send (internal/child_process.js:597:19)
    at Timeout.setInterval [as _onTimeout] (C:\Users\pax07\node_modules\homebridge-config-ui-x\src\index.ts:60:10)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
```

**Comment by paolotremadio** [comment]
Hi, are you sure it is due to the chromecast plugin? It looks like an error with the `homebridge-config-ui-x` plugin...

**Comment by pax0707** [comment]
Yeah. My bad.

I've noticed that while writing it and opened that repo in another tab.
Must have posted in wrong tab.
