### ISSUE TITLE
Fail to load plugin. `SyntaxError: Unexpected token )`

### ISSUE THREAD

**Issue by sbehrends** [paolotremadio/homebridge-automation-chromecast#3]
Installed the plugin with ``, added the accessory to configuration.

When homebridge initializes exits with an error that could not load the plugin because of an Unexpected token.

```
[8/5/2018, 1:54:24 AM] ====================
[8/5/2018, 1:54:24 AM] ERROR LOADING PLUGIN homebridge-automation-chromecast:
[8/5/2018, 1:54:24 AM] /usr/lib/node_modules/homebridge-automation-chromecast/index.js:245
          );
          ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:72:22)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:142:14)
[8/5/2018, 1:54:24 AM] ====================
```

**Comment by sbehrends** [comment]
Had node 7.x installed on raspberry. Upgraded 10.8, rebuild every module and now it's working as expected ;)

**Comment by paolotremadio** [comment]
Hi, thanks for opening this issue. I've now updated the package.json to require node v8 or newer 😊

Also, feel free to share what automations you are going to create. I'm curious to find out what features could be added to this plugin.

Cheers!
