### ISSUE TITLE
Should playing stream to ChromecastAudio turn the Homebridge switch "On"?

### ISSUE THREAD

**Issue by CubGeek** [paolotremadio/homebridge-automation-chromecast#4]
Hello, and thanks for the plugin.  I'm just getting into the world of Homebridge and plugins, and really like the concept of the plugin.

I'm confused, however, as to if the switch for the plugin's accessory in Elgato Eve app (simple on/off toggle) is supposed to turn ON when I begin casting to the device.  My understanding is that it is supposed to, yes, and it also activates the virtual motion sensor with positive "movement" too.  And that, once the stream is stopped and no more data is being sent to the device, the switch then goes to OFF and the motion sensor will be turned off after the switchOffDelay value.

The reason I ask is because I'm experiencing an issue where I can stream audio to my ChromecastAudio, but the plugin does not activate the "ON/OFF" switch.  Neither is there any information in the Homebridge .err or .log files for activation (or errors related thereunto).

If I go into the Elgato Eve app and manually activate the switch, or turn it off, I see in the homebridge.log:
```
[1/25/2019, 1:43:16 AM] [ChromecastAudio] Searching for Chromecast device named "ChromecastAudio>"
[1/25/2019, 1:45:17 AM] [ChromecastAudio] Chromecast is now playing
[1/25/2019, 1:45:17 AM] [ChromecastAudio] Motion sensor is detecting movements
[1/25/2019, 1:48:40 AM] [ChromecastAudio] Chromecast is now stopped
[1/25/2019, 1:48:50 AM] [ChromecastAudio] Motion sensor stopped detecting movements
```
However, that's it.  Any ideas? stats are:

Ubuntu 18.04 LTS
node v11.7.0
homebridge v0.4.45
homebridge-hue v0.11.11
homebridge-automation-chromecast v1.0.3

(this is my very first post to Git, so please forgive me if I've missed any information)

**Comment by paolotremadio** [comment]
Hey, can you please provide the log of homebridge before, during and after you streaming to your chromecast device? Just to see what's going on there. Can you also start playing music, terminate your Eve app and open it again? it could be an issue with Eve not detecting the state change of the switch.

The motion sensor is used to trigger automation. The switch is used to start/stop the music.

For example, you start playing music, the motion sensor detects movement and the switch is turned on. If you turn off the switch, music will be paused. If you turn on the switch again, music will restart. That could be useful in conjunction with a physical button (so you can have a remote to play/pause music).

**Comment by CubGeek** [comment]
Hello!

Here's the /var/log/homebridge.log, from a service start:
```
[1/27/2019, 8:13:14 PM] Loaded config.json with 1 accessories and 4 platforms.
[1/27/2019, 8:13:14 PM] ---
[1/27/2019, 8:13:16 PM] Loaded plugin: homebridge-automation-chromecast
[1/27/2019, 8:13:16 PM] Registering accessory 'homebridge-automation-chromecast.AutomationChromecast'
[1/27/2019, 8:13:16 PM] ---
[1/27/2019, 8:13:18 PM] Loaded plugin: homebridge-dacp
[1/27/2019, 8:13:18 PM] Registering platform 'homebridge-dacp.DACP'
[1/27/2019, 8:13:18 PM] ---
[1/27/2019, 8:13:20 PM] Loaded plugin: homebridge-hue
[1/27/2019, 8:13:20 PM] Registering platform 'homebridge-hue.Hue'
[1/27/2019, 8:13:20 PM] ---
[1/27/2019, 8:13:20 PM] Loaded plugin: homebridge-seasons
[1/27/2019, 8:13:20 PM] Registering platform 'homebridge-seasons.Seasons'
[1/27/2019, 8:13:20 PM] ---
[1/27/2019, 8:13:21 PM] Loaded plugin: homebridge-weather-plus
[1/27/2019, 8:13:21 PM] Registering platform 'homebridge-weather-plus.WeatherPlus'
[1/27/2019, 8:13:21 PM] ---
[1/27/2019, 8:13:21 PM] Loading 4 platforms...
[1/27/2019, 8:13:21 PM] [Hue] Initializing Hue platform...
[1/27/2019, 8:13:22 PM] [Hue] homebridge-hue v0.11.11, node v11.7.0, homebridge v0.4.45
[1/27/2019, 8:13:22 PM] [WeatherPlus] Initializing WeatherPlus platform...
[1/27/2019, 8:13:22 PM] [WeatherPlus] Initializing platform accessory 'Now'...
[1/27/2019, 8:13:22 PM] [WeatherPlus] Initializing platform accessory 'Today'...
[1/27/2019, 8:13:22 PM] [WeatherPlus] Initializing platform accessory 'In 1 Day'...
[1/27/2019, 8:13:22 PM] [WeatherPlus] Initializing platform accessory 'In 2 Days'...
[1/27/2019, 8:13:22 PM] [Seasons] Initializing Seasons platform...
[1/27/2019, 8:13:22 PM] [Seasons] Initializing platform accessory 'Season'...
[1/27/2019, 8:13:22 PM] [DACP] Initializing DACP platform...
[1/27/2019, 8:13:22 PM] [DACP] DACP Platform Plugin Loaded - Version 0.9.2
[1/27/2019, 8:13:22 PM] [DACP] Found accessory in config: "iTunes"
[1/27/2019, 8:13:22 PM] [DACP] Initializing platform accessory 'iTunes'...
[1/27/2019, 8:13:22 PM] Loading 1 accessories...
[1/27/2019, 8:13:22 PM] [ChromecastAudio] Initializing AutomationChromecast accessory...
[1/27/2019, 8:13:22 PM] [ChromecastAudio] Searching for Chromecast device named "ChromecastAudio>"
[1/27/2019, 8:13:22 PM] [DACP] Starting DACP browser...
[1/27/2019, 8:13:23 PM] [DACP] The accessory iTunes is announced as 192.168.0.90:3689.
[1/27/2019, 8:13:23 PM] [DACP] It's an iTunes named Kosh’s Library
[1/27/2019, 8:13:23 PM] [DACP] Attempting to reconnect to iTunes in 0.1 seconds.
[1/27/2019, 8:13:23 PM] [DACP] Connecting to iTunes (192.168.0.90:3689)
[1/27/2019, 8:13:23 PM] [DACP] Creating status connection to 192.168.0.90:3689
Established connection to 192.168.0.90:3689 with session ID 1822013762
[1/27/2019, 8:13:23 PM] [DACP] Connected to Kosh’s Library
[1/27/2019, 8:13:23 PM] [DACP] Creating properties connection to 192.168.0.90:3689
[1/27/2019, 8:13:23 PM] [DACP] Updating characteristics with current volume: v=62
[1/27/2019, 8:13:27 PM] [Hue] Philips hue: Philips BSB002 bridge v1811120916, api v1.29.0
[1/27/2019, 8:13:28 PM] [Hue] Philips hue: 6 accessories
[1/27/2019, 8:13:28 PM] [Hue] masked debug info dumped to /var/homebridge/homebridge-hue.json.gz
[1/27/2019, 8:13:28 PM] [Hue] Initializing platform accessory 'Philips hue'...
[1/27/2019, 8:13:28 PM] [Hue] Philips hue: 3 services
[1/27/2019, 8:13:28 PM] [Hue] Initializing platform accessory 'Stairs plug'...
[1/27/2019, 8:13:28 PM] [Hue] Initializing platform accessory 'Master bedroom underbed'...
[1/27/2019, 8:13:28 PM] [Hue] Initializing platform accessory 'On/Off plug 1'...
[1/27/2019, 8:13:28 PM] [Hue] Initializing platform accessory 'Color light 1'...
[1/27/2019, 8:13:28 PM] [Hue] Initializing platform accessory 'Color light 2'...
Setup Payload:
X-HM://0023ISYWYK434
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
[1/27/2019, 8:13:28 PM] Homebridge is running on port 51826.
[1/27/2019, 8:19:10 PM] [DACP] Returning current mute state: v=false
[1/27/2019, 8:19:10 PM] [DACP] Returning current volume: v=62
[1/27/2019, 8:19:27 PM] [DACP] Returning current playback state: paused
[1/27/2019, 8:43:12 PM] Got SIGTERM, shutting down Homebridge...
```
From timestamp 8:19:27 PM until 8:40:15 or so, I began streaming music to the Chromecast Audio from a Chrome tab on my computer using a youtube video.  Music was playing through the speakers, after about 25 minutes. I stopped casting and then at 8:43:12 I sent the SERVICE HOMEBRIDGE STOP command.  At no time during this did the Eve app recognize that the ChromecastAudio was in use. The switch was OFF and the Streaming sensor was "CLEAR."

For the next experiment, I started casting _before_ I started the homebridge service.  Again, sound was coming from the speakers. I made sure that the Eve app was closed, as well.

/var/log/homebridge.log file for this (only about 4 minutes):
```
[1/27/2019, 9:03:02 PM] Loaded config.json with 1 accessories and 4 platforms.
[1/27/2019, 9:03:03 PM] ---
[1/27/2019, 9:03:03 PM] Loaded plugin: homebridge-automation-chromecast
[1/27/2019, 9:03:03 PM] Registering accessory 'homebridge-automation-chromecast.AutomationChromecast'
[1/27/2019, 9:03:03 PM] ---
[1/27/2019, 9:03:04 PM] Loaded plugin: homebridge-dacp
[1/27/2019, 9:03:04 PM] Registering platform 'homebridge-dacp.DACP'
[1/27/2019, 9:03:04 PM] ---
[1/27/2019, 9:03:05 PM] Loaded plugin: homebridge-hue
[1/27/2019, 9:03:05 PM] Registering platform 'homebridge-hue.Hue'
[1/27/2019, 9:03:05 PM] ---
[1/27/2019, 9:03:05 PM] Loaded plugin: homebridge-seasons
[1/27/2019, 9:03:05 PM] Registering platform 'homebridge-seasons.Seasons'
[1/27/2019, 9:03:05 PM] ---
[1/27/2019, 9:03:06 PM] Loaded plugin: homebridge-weather-plus
[1/27/2019, 9:03:06 PM] Registering platform 'homebridge-weather-plus.WeatherPlus'
[1/27/2019, 9:03:06 PM] ---
[1/27/2019, 9:03:06 PM] Loading 4 platforms...
[1/27/2019, 9:03:06 PM] [Hue] Initializing Hue platform...
[1/27/2019, 9:03:06 PM] [Hue] homebridge-hue v0.11.11, node v11.7.0, homebridge v0.4.45
[1/27/2019, 9:03:06 PM] [WeatherPlus] Initializing WeatherPlus platform...
[1/27/2019, 9:03:07 PM] [WeatherPlus] Initializing platform accessory 'Now'...
[1/27/2019, 9:03:07 PM] [WeatherPlus] Initializing platform accessory 'Today'...
[1/27/2019, 9:03:07 PM] [WeatherPlus] Initializing platform accessory 'In 1 Day'...
[1/27/2019, 9:03:07 PM] [WeatherPlus] Initializing platform accessory 'In 2 Days'...
[1/27/2019, 9:03:07 PM] [Seasons] Initializing Seasons platform...
[1/27/2019, 9:03:07 PM] [Seasons] Initializing platform accessory 'Season'...
[1/27/2019, 9:03:07 PM] [DACP] Initializing DACP platform...
[1/27/2019, 9:03:07 PM] [DACP] DACP Platform Plugin Loaded - Version 0.9.2
[1/27/2019, 9:03:07 PM] [DACP] Found accessory in config: "iTunes"
[1/27/2019, 9:03:07 PM] [DACP] Initializing platform accessory 'iTunes'...
[1/27/2019, 9:03:07 PM] Loading 1 accessories...
[1/27/2019, 9:03:07 PM] [ChromecastAudio] Initializing AutomationChromecast accessory...
[1/27/2019, 9:03:07 PM] [ChromecastAudio] Searching for Chromecast device named "ChromecastAudio>"
[1/27/2019, 9:03:07 PM] [DACP] Starting DACP browser...
[1/27/2019, 9:03:08 PM] [DACP] The accessory iTunes is announced as 192.168.0.90:3689.
[1/27/2019, 9:03:08 PM] [DACP] It's an iTunes named Kosh’s Library
[1/27/2019, 9:03:08 PM] [DACP] Attempting to reconnect to iTunes in 0.1 seconds.
[1/27/2019, 9:03:08 PM] [DACP] Connecting to iTunes (192.168.0.90:3689)
[1/27/2019, 9:03:08 PM] [DACP] Creating status connection to 192.168.0.90:3689
Established connection to 192.168.0.90:3689 with session ID 627054146
[1/27/2019, 9:03:08 PM] [DACP] Connected to Kosh’s Library
[1/27/2019, 9:03:08 PM] [DACP] Creating properties connection to 192.168.0.90:3689
[1/27/2019, 9:03:08 PM] [DACP] Updating characteristics with current volume: v=62
[1/27/2019, 9:03:12 PM] [Hue] Philips hue: Philips BSB002 bridge v1811120916, api v1.29.0
[1/27/2019, 9:03:12 PM] [Hue] Philips hue: 6 accessories
[1/27/2019, 9:03:12 PM] [Hue] masked debug info dumped to /var/homebridge/homebridge-hue.json.gz
[1/27/2019, 9:03:12 PM] [Hue] Initializing platform accessory 'Philips hue'...
[1/27/2019, 9:03:12 PM] [Hue] Philips hue: 3 services
[1/27/2019, 9:03:12 PM] [Hue] Initializing platform accessory 'Stairs plug'...
[1/27/2019, 9:03:12 PM] [Hue] Initializing platform accessory 'Master bedroom underbed'...
[1/27/2019, 9:03:12 PM] [Hue] Initializing platform accessory 'On/Off plug 1'...
[1/27/2019, 9:03:12 PM] [Hue] Initializing platform accessory 'Color light 1'...
[1/27/2019, 9:03:12 PM] [Hue] Initializing platform accessory 'Color light 2'...
Setup Payload:
X-HM://0023ISYWYK434
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
[1/27/2019, 9:03:13 PM] Homebridge is running on port 51826.
[1/27/2019, 9:03:21 PM] [DACP] Returning current mute state: v=false
[1/27/2019, 9:03:21 PM] [DACP] Returning current volume: v=62
[1/27/2019, 9:06:42 PM] Got SIGTERM, shutting down Homebridge...
```
No entry for the ChromecastAudio, again, and when I opened the Eve app the ChromecastAudio switch was OFF and the ChromecastAudio Streaming was CLEAR.

Reading the logs, it seems that the accessory may not be found? see:
```
[1/27/2019, 9:03:07 PM] [ChromecastAudio] Initializing AutomationChromecast accessory...
[1/27/2019, 9:03:07 PM] [ChromecastAudio] Searching for Chromecast device named "ChromecastAudio>"
```
It starts searching for the accessory, but I don't see an entry that it successfully bound to it.  Possibly part of the problem?

The relevant part of the config.json is:
```
   "accessories": [{
                        "accessory": "AutomationChromecast",
                        "name": "ChromecastAudio",
                        "chromecastDeviceName": "ChromecastAudio>",
                        "switchOffDelay": 10000}]
```

I've attached a screenshot of the chromecast config page, too.  Just in case... :) 
![cca-info](https://user-images.githubusercontent.com/35697216/51807011-28931780-224f-11e9-8c49-9767164c50a3.PNG)

Thanks for the assistance!

**Comment by CubGeek** [comment]
`**facepalm**`

I just saw the "ChromecastAudio>" as the device name in the config.json file.  Going to try removing that and restarting the homebridge service.  Will update in a moment.  (boy I feel dumb).

**Comment by CubGeek** [comment]
No, that seemed to make things worse.  LOL 

In the config.json, I'm having issues now.  I removed the ">" from the device name, and now I'm getting config.json errors.  Here's my file:

```
{
	"bridge": {
		"name": "Homebridge",
		"username": "00:00:00:00:00:00",
		"port": 51826,
		"pin": "000-00-000"
	},
	"description": "Koshs basic config file.",
	"platforms": [{
			"platform": "Hue",
			"name": "Hue",
			"users": {
				"0000000000": "00000-000000000-00000000000"
			},
			"lights": true,
			"nativeHomeKitLights": true
		},
		{
			"platform": "WeatherPlus",
			"name": "WeatherPlus",
			"service": "darksky",
			"key": "00000000000000000000000000000000",
			"locationGeo": [12.3456, -12.3456],
			"language": "en",
			"forecast": [1, 2, 3]
		},
		{
			"platform": "Seasons",
			"name": "Seasons",
			"calendar": "meteorologic",
			"hemisphere": "north",
			"display": "both"
		},
		{
			"platform": "DACP",
			"devices": [{
				"name": "iTunes",
				"pairing": "0000000000000000",
				"serviceName": "0000000000000000",
				"playlists": ["Chill", "Moving", "Staging"]
			}]
		},
		{
			"accessories": [{
				"accessory": "AutomationChromecast",
				"name": "ChromecastAudio",
				"chromecastDeviceName": "ChromecastAudio",
				"switchOffDelay": 10000
			}]
		}
	]
}
```

Running the service now, in the /var/log/homebridge.err file I see:

```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
[1/28/2019, 4:48:26 AM] Plugin /usr/lib/node_modules/homebridge-hue requires Node version of ^10.15.0 which does not satisfy the current Node version of v11.7.0. You may need to upgrade your installation of Node.
2019-01-28T04:48:28.450Z HueDiscovery1 constructor({"timeout":5})
2019-01-28T04:48:28.469Z OptionParser0 constructor({"timeout":5}, false)
2019-01-28T04:48:28.471Z OptionParser0 boolKey("verbose")
2019-01-28T04:48:28.472Z OptionParser0 intKey("timeout", 1, 60)
2019-01-28T04:48:28.473Z OptionParser0 parse({"timeout":5})
2019-01-28T04:48:28.474Z OptionParser0 parse() => {"timeout":5}
2019-01-28T04:48:28.475Z HueDiscovery1 constructor({"timeout":5}) => {"timeout":5}
[1/28/2019, 4:48:28 AM] [Hue] warning: not using recommended node version v10.15.0 LTS
Mon, 28 Jan 2019 04:48:28 GMT homebridge-weather-plus Init platform
Mon, 28 Jan 2019 04:48:28 GMT homebridge-weather-plus Using service dark sky
Mon, 28 Jan 2019 04:48:28 GMT homebridge-weather-plus Called hourly update of rain data
/usr/lib/node_modules/homebridge/lib/api.js:108
  if (name.indexOf('.') == -1) {
           ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:108:12)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:316:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```
The avahi compatability issue is expected.  However, if I remove the AutomationChromecast section (Accessories) entirely, Homebridge starts up and runs without a problem.  But now I can't see the chromecast switch or motion sensor.  LOL  Time to sleep on this and maybe fresh eyes in the morning can see something I'm not right now.

**Comment by CubGeek** [comment]
Seems that there is some underlying issues on the system running my instance of Homebridge. Closing this issue as I'm not 100% sure the issue is related to this plugin.  My apologies!

**Comment by paolotremadio** [comment]
Feel free to re-open the issue whenever you have more details 😊
