### ISSUE TITLE
Homebridge crashes

### ISSUE THREAD

**Issue by Salvora** [paolotremadio/homebridge-automation-chromecast#9]
Hello,
This always crashes. I am getting below error.

What may be the problem?

```
Error: getaddrinfo -3008
    at errnoException (/homebridge/node_modules/homebridge-automation-chromecast/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
    at getaddrinfo_complete (/homebridge/node_modules/homebridge-automation-chromecast/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
    at GetAddrInfoReqWrap.oncomplete (/homebridge/node_modules/homebridge-automation-chromecast/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)
```

**Comment by paolotremadio** [comment]
Which Linux distro are you using (including version)? What device are you running it on?

Any particular network setup?

**Comment by Salvora** [comment]
I am running homebridge on Synology NAS DS1815+ docker with oznu/homebridge-syno-spk. Just a straight network without any vlans and such.

**Comment by paolotremadio** [comment]
It might be an issue with the docker container. I will try to reproduce but I’m not expecting good results. Do you have any other bonjour/mdns based plugin installed in the same docker container?

**Comment by Salvora** [comment]
Nope. My docker only has homebridge container.

**Comment by paolotremadio** [comment]
Closing this. It looks lie there's an issue with Docker. I would recommend to run it directly on the host. See https://github.com/paolotremadio/homebridge-automation-chromecast/issues/11
